version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=quartz
    volumes:
      - "./src/main/resources/schema:/docker-entrypoint-initdb.d"

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080

  app:
    image: spring-quartz:1.0.0
    deploy:
      replicas: 2
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
